### ISSUE TITLE
OZ is a devDependency in package.json

### ISSUE THREAD

**Issue by eMarchenko** [Uniswap/merkle-distributor#17]
HI! Could you explain me, why OZ library is considered to be a devDependency?

![image](https://user-images.githubusercontent.com/7409234/131490366-4ea7dcbc-2393-4b8c-8f4f-6b372d5ae4f3.png)

I usually add it as a dependency, as it is required for the contracts. What is the best practice?

**Comment by ronielex** [comment]
Learn and teach me how to use this oz Library for the new user like me. To understand please. Thank you.

**Comment by NoahZinsmeister** [comment]
closed by 42f7a9e1260bb58a1257b43513e5fecd6140de99
