### ISSUE TITLE
Clawback extension

### ISSUE THREAD

**Issue by smartcontracts** [Uniswap/merkle-distributor#28]
Clawbacks of unclaimed tokens after X amount of time is a relatively common usecase. I'd like to propose either extending the existing contract or adding a second contract that inherits from the primary MerkleDistributor and handles clawbacks. I'd be happy to implement this.

**Comment by marktoda** [comment]
like this? https://github.com/Uniswap/merkle-distributor/blob/25a79e8ec8c22076a735b1a675b961c8184e7931/contracts/MerkleDistributorWithDeadline.sol#L27

**Comment by smartcontracts** [comment]
Lawl I'm an idiot, I was looking at an old commit

**Comment by smartcontracts** [comment]
Thanks!
