### ISSUE TITLE
anyone can call `claim` ?

### ISSUE THREAD

**Issue by rkart14** [Uniswap/merkle-distributor#9]
Let's imagine this scenario.

We build the merkle tree with `userA, userB, userC` and their respective amounts (10,20,30) with the indexes (0,1,2). We get the merkle root and create this `merkle-distributor` contract with it.

Now, it's possible that `userB` calls `claim` function and passes `userA`'s address, index and amount and also proof. This will make sure that `userB` is able to make the transfer from `merkle-distributor` to `userA` without even `userA`'s interaction and consent, which seems kind of wrong.

Of course,  `userB` can quickly figure out the proof, address, index and amount of `userA`. So that's not the obstacle.

Am i missing something ?

Thanks in advance.

**Comment by NoahZinsmeister** [comment]
this is intended. any address should be able to claim on behalf of any other, there's no security concerns, and there can be UX benefits

**Comment by rkart14** [comment]
Thanks for answering @NoahZinsmeister .. Really appreciated.

Could you bring one good use case why using `merkle-distributor` would be a good benefit ?

**Comment by serinuntius** [comment]
Of course, the basic premise is that Uniswap is not at fault, but this system, which anyone can call, triggers fraud.

The scenario is as follows. The scammer says, "I accidentally sent $Paint to your address. Can you please return half of it?"

The person who doesn't know anything doesn't realize that his or her Claimable $Paint has been sent, so he or she is tempted to send half the $Paint.

This scam is quite clever and I think quite a few people will fall for it.

Why not prioritize fraud eradication over UX benefits?
